import Link from "next/link";
import { useRecoilValue } from "recoil";

import {
  Container,
  Table,
  Tbody,
  Td,
  Text,
  Th,
  Thead,
  Tr,
  Box,
  Button,
} from "@chakra-ui/react";

import Router from "next/router";
import { postsState } from "./atoms/atom";
import Head from "next/head";
import { AddIcon } from "@chakra-ui/icons";
import Header from "../src/components/Header";
import BackButton from "../src/components/atoms/button/BackButton";
import EditButton from "../src/components/atoms/button/EditButton";
const handler = (path) => {
  Router.push(path);
};

const Edit = () => {
  const posts = useRecoilValue(postsState);

  return (
    <>
      <Head>
        <title>みんなの質問</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Container
        h="100vh"
        minH="100%"
        maxW="100%"
        bg="#DDE3DE"
        m="0"
        padding="1rem"
      >
        <Header />
        <Container minH="calc(100% - 64px)" maxW="100%" bg="white" padding="5">
          <Box mt="10" mr="5" textAlign="right">
            <Button
              background="#F4D1AE"
              _hover={{ opacity: "0.8" }}
              onClick={() => handler("/posting")}
            >
              <AddIcon mr="2" />
              新規投稿
            </Button>
          </Box>
          <Container h="100%" maxW="100%" mt="5">
            <Table>
              <Thead bg="#F4EDEA">
                <Tr>
                  <Th>名前</Th>
                  <Th>質問内容</Th>
                  <Th>作成日時</Th>
                </Tr>
              </Thead>

              <Tbody>
                {posts.map((post) => (
                  <Tr key={post.id}>
                    <Td h="65.5px">
                      <Link href={`/todos/${post.id}`} passHref>
                        <Text
                          cursor="pointer"
                          _hover={{ opacity: 0.7 }}
                          lineHeight="32.5px"
                        >
                          {post.name}
                        </Text>
                      </Link>
                    </Td>

                    <Td>
                      <Box display="flex">
                        <Text lineHeight="40px">{post.title}</Text>

                        <EditButton
                          onClick={() => handler(`/user/${post.id}/edit`)}
                       />
                        

                      </Box>
                    </Td>
                    <Td>{post.createDate}</Td>
                  </Tr>
                ))}
              </Tbody>
            </Table>
          </Container>
          <Box pos="absolute" bottom="8" right="0">
            <BackButton />
          </Box>
        </Container>
      </Container>
    </>
  );
};

export default Edit;
