// 新規投稿画面
import {
  Box,
  Container,
  Divider,
  Flex,
  FormControl,
  FormLabel,
  Input,
  Spacer,
  Stack,
  Textarea,
} from "@chakra-ui/react";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import Header from "../src/components/Header";
import BackButton from "../src/components/atoms/button/BackButton";
import UserButton from "../src/components/atoms/button/UserButton";
import styles from "../styles/Container.module.css";
import UseAddPost from "../src/hooks/UseAddPost";
import Router from "next/router";
import { useRecoilState } from "recoil";
import { postsState } from "../src/atoms/atom";
import { db } from "../src/base/firebase";
const handler = (path) => {
  Router.push(path);
};

const user = () => {
  const [addName, setAddName] = useState("");
  const [addTitle, setAddTitle] = useState("");
  const [addText, setAddText] = useState("");
  // Post追加用カスタムフック
  const { newQuestion } = UseAddPost();

  // const [posts,setPosts] = useRecoilState(postsState)
  // useEffect(() => {
  //   const unSub = db.collection("question").onSnapshot((snapshot) => {
  //     setPosts(
  //       snapshot.docs.map((doc) => ({
  //         id: doc.id,
  //         title: doc.data().title,
  //         name: doc.data().name,
  //         text: doc.data().text
  //       }))
  //     );
  //   });
  //   return () => unSub();
  // }, []);

  return (
    <>
      <Head>
        <title>みんなの質問</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Container className={styles.mainContainer}>
        <Header />
        <Container className={styles.subContainer}>
          <form>
            <Container py={["20px", "60px"]} maxW="container.lg">
              <Stack spacing={[2, 6]}>
                <FormControl>
                  <Flex direction={["column", "row"]}>
                    <Flex minW={24} width={24}>
                      <FormLabel>名前</FormLabel>
                      <Spacer />
                      <Box>:</Box>
                    </Flex>
                    <Box>
                      <Input
                        ml={[0, 6]}
                        borderColor="#bebaba"
                        borderWidth="2px"
                        value={addName}
                        onChange={(e) => setAddName(e.target.value)}
                      />
                    </Box>
                  </Flex>
                </FormControl>
                <Divider borderColor="gray" borderBottomWidth="2px" />
                <FormControl>
                  <Flex direction={["column", "row"]}>
                    <Flex minW={24} width={24}>
                      <FormLabel>タイトル</FormLabel>
                      <Spacer />
                      <Box>:</Box>
                    </Flex>
                    
                      <Input
                        ml={[0, 6]}
                        borderColor="#bebaba"
                        borderWidth="2px"
                        h="32px"
                        value={addTitle}
                        onChange={(e) => setAddTitle(e.target.value)}
                      />
                    
                  </Flex>
                </FormControl>
                <Divider borderColor="gray" borderBottomWidth="2px" />
                <FormControl>
                  <Flex minH={44} direction={["column", "row"]}>
                    <Flex minW={24} width={24}>
                      <FormLabel>質問内容</FormLabel>
                      <Spacer />
                      <Box>:</Box>
                    </Flex>
                    <Textarea
                      ml={[0, 6]}
                      borderColor="#bebaba"
                      borderWidth="2px"
                      h="180px"
                      value={addText}
                      onChange={(e) => setAddText(e.target.value)}
                    />
                  </Flex>
                </FormControl>
                <Divider borderColor="gray" borderBottomWidth="2px" />
              </Stack>
            </Container>
            <Spacer />
            <Box pos="absolute" bottom="8" right="0">
              <BackButton onClick={() => handler("/user")} />
              <UserButton
                text={"保存"}
                colorScheme={"blue"}
                onClick={() => newQuestion(addName, addTitle, addText)}
              />
            </Box>
          </form>
        </Container>
      </Container>
    </>
  );
};

export default user;
