import { Container } from "@chakra-ui/react";
import Head from "next/head";
import QuestionList from "../src/components/QuestionList";
import Header from "../src/components/Header";

const user = () => {
  return (
    <>
      <Head>
        <title>みんなの質問</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Container
        h="100vh"
        minH="100%"
        maxW="100%"
        bg="#DDE3DE"
        m="0"
        padding="1rem"
      >
        <Header />

        <Container minH="calc(100% - 64px)" maxW="100%" bg="white" padding="5">
          <QuestionList />
        </Container>
      </Container>
    </>
  );
};

export default user;
