// 質問一覧画面
import { Container } from "@chakra-ui/react";
import Head from "next/head";
import PostList from "../src/components/QuestionList";
import Header from "../src/components/Header";
import styles from "../styles/Container.module.css"

const useList = () => {
  return (
    <>
      <Head>
        <title>edTalk</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Container className={styles.mainContainer}>
        <Header titleName={"edtalk"}/>
        <Container className={styles.subContainer} bg="#028090">
          <PostList />
        </Container>
      </Container>
    </>
  );
};

export default useList;
